### ISSUE TITLE
Typescript version?

### ISSUE THREAD

**Issue by jonathansolorzn** [darksinge/deep-cleaner#7]
Does this support typescript?

**Comment by darksinge** [comment]
First of all, sorry for the really long reply...

I haven't tested that it works with Typescript, so I couldn't tell you. I'm not very familiar with Typescript but I would welcome a pull request. Between work, life, all the things, etc., I won't have the time to figure it out for a while.

**Comment by ghaschel** [comment]
I use it with typescript.
Just import it like 
`import deepCleaner from 'deep-cleaner'`
